backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: data/media
public_folder: media

collections:
  - name: "pages"
    label: "Pages"
    description: "You can edit the pages of your website here"
    files:
      - label: 'Home'
        name: 'home'
        file: data/pages/home.json
        delete: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string' }
          - {label: 'Title Underlined', name: 'underlinedTitle', widget: 'string'}
          - {label: 'Slogan', name: 'slogan', widget: 'string' }
          - label: 'Cover Image'
            name: 'image'
            widget: 'image'
            required: true
            tagname: ''
          - label: 'Service Block'
            name: 'serviceBlock'
            widget: 'object'
            fields:
              - label: "Services"
                name: "services"
                minimize_collapsed: true
                widget: "list"
                fields:
                  - {label: "Color", name: "color", widget: "string"}
                  - {label: "Icon", name: "icon", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
                  - {label: "Animation", name: "animation", widget: "select", default: "fade-up", options: ["fade-up", "fade-down", "fade-left", "fade-right", "fade-up-right", "fade-up-left", "zoom-in", "zoom-in-left", "zoom-in-right"]}
              - label: 'Featured'
                name: 'featured'
                widget: 'object'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Description', name: 'description', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}
              - label: 'Content'
                name: 'content'
                widget: 'markdown'
          - label: 'Build Block'
            name: 'buildBlock'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: string}
              - {label: 'Description', name: 'description', widget: string}
              - label: "Items"
                name: "items"
                minimize_collapsed: true
                widget: "list"
                fields:
                  - {label: "Icon", name: "icon", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
                  - {label: "Animation", name: "animation", widget: "select", default: "fade-up", options: ["fade-up", "fade-down", "fade-left", "fade-right", "fade-up-right", "fade-up-left", "zoom-in", "zoom-in-left", "zoom-in-right"]}
              - label: 'Featured'
                name: 'featured'
                widget: 'object'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Description', name: 'description', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}

      - label: 'About'
        name: 'about'
        file: data/pages/about.json
        delete: false
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: "Image", name: "thumbnail", widget: "image" }

      - label: 'Portfolio' # Used in the UI
        name: 'portfolio'
        file: 'data/pages/portfolio.json'
        fields:
          - {label: 'Title', name: 'title', widget: 'string' }
          - {label: 'Title Underlined', name: 'underlinedTitle', widget: 'string'}
          - {label: 'Slogan', name: 'slogan', widget: 'string', required: false }
          - label: 'Cover Image'
            name: 'image'
            widget: 'image'
            required: true
            tagname: ''

      - label: 'Contact'
        name: 'contact'
        file: data/pages/contact.json
        delete: false
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: "Image", name: "thumbnail", widget: "image" }

  - label: 'Jobs' # Used in the UI
    name: 'jobs'
    label_singular: 'Job' # Used in the UI, ie: "New Post"
    title: "Works we've are proud of"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: '_jobs'
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    view_filters:
      - label: Jobs With Index
        field: title
        pattern: 'This is a job #'
      - label: Drafts
        field: draft
        pattern: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Job Name' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Cover Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: "settings"
    label: "Settings"
    delete: false
    description: "Manage settings including your sites title, description and keywords."
    summary: "Metadata"
    files:
      - label: 'Metadata'
        name: 'metadata'
        file: data/settings.json
        delete: false
        fields:
          - { label: "Site title", name: "site_title", widget: "string" }
          - { label: "Site description", name: "site_description", widget: "string" }
          - { label: "URL", name: "base_url", widget: "string", hint: "Do not enter the trailing slash of the URL" }
          - { label: "Preview thumbnail", name: "thumbnail", widget: "image" }
          - { label: "Site keywords", name: "site_keywords", widget: "string", hint: 'Use a comma to separate keywords. E.g Photography, Portfolio, Prints'}
          - { label: "Instagram account", name: "instagram_account", widget: "string" }